version: 2

jobs:
  build:
    machine:
      image: windows-server-2019-nvidia:stable

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
